FROM amd64/alpine:3.21@sha256:0fcdd3eb862c094cd75cf76bd7acd105e2927f69565a595899d76bc33512e37f AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9506
ENTRYPOINT ["/usr/bin/jenkins_exporter"]
HEALTHCHECK CMD ["/usr/bin/jenkins_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/jenkins_exporter /usr/bin/jenkins_exporter
