FROM i386/alpine:3.20@sha256:fa66aa594ffa884dff44f4a97821756545834505df611c375a30c45926402f89 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9506
ENTRYPOINT ["/usr/bin/jenkins_exporter"]
HEALTHCHECK CMD ["/usr/bin/jenkins_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/jenkins_exporter /usr/bin/jenkins_exporter
