FROM arm64v8/alpine:3.18@sha256:e3bd82196e98898cae9fe7fbfd6e2436530485974dc4fb3b7ddb69134eda2407 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9506
ENTRYPOINT ["/usr/bin/jenkins_exporter"]
HEALTHCHECK CMD ["/usr/bin/jenkins_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/jenkins_exporter /usr/bin/jenkins_exporter
