FROM arm32v6/alpine:3.21@sha256:9eb920e2ac62ae9ded9d084180d2f112823f8d4bcece2d13c5afdec326454100 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9506
ENTRYPOINT ["/usr/bin/jenkins_exporter"]
HEALTHCHECK CMD ["/usr/bin/jenkins_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/jenkins_exporter /usr/bin/jenkins_exporter
