FROM arm64v8/alpine:3.17@sha256:c41ab5c992deb4fe7e5da09f67a8804a46bd0592bfdf0b1847dde0e0889d2bff AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9506
ENTRYPOINT ["/usr/bin/jenkins_exporter"]
HEALTHCHECK CMD ["/usr/bin/jenkins_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/jenkins_exporter /usr/bin/jenkins_exporter
